// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   /**
    * public static final class DriveConstants {
    *   public static final int kLeftMotor1Port = 0;
    *   public static final int kLeftMotor2Port = 1;
    *   public static final int kRightMotor1Port = 2;
    *   public static final int kRightMotor2Port = 3; 
    * }
    */ 
    //ArmConstants
    public static final double kARM_LIFT = 999999.345;  // Very large number that is unlikely to ever be used as a parameter
    public static final double kARM_LOWER = -999999.345;  // Very large number that is unlikely to ever be used as a parameter
    public static final double kARM_MOVE_RATE = 1.0;  // Rate per button press
    //WristConstants
    public static final double kWrist_Tilt_UP = 999999.345;  // Very large number that is unlikely to ever be used as a parameter
    public static final double kWrist_Tilt_DOWN = -999999.345;  // Very large number that is unlikely to ever be used as a parameter
    public static final double kWRIST_MOVE_RATE = 1.0;  // Rate per button press
    //ElevatorConstants
    public static final double kElevator_Nudge_UP = 999999.345;  // Very large number that is unlikely to ever be used as a parameter
    public static final double kElevator_Nudge_Down = -999999.345;  // Very large number that is unlikely to ever be used as a parameter
    public static final double kElevator_MOVE_RATE = 1.0;  // Rate per button press
    // All arm servos
    public static final double kHOLD_SERVO_STATE = 987654.59687;  // Very large number that is unlikely to ever be used as a parameter
}

